### ISSUE TITLE
Slow append

### ISSUE THREAD

**Issue by Archetipo95** [icyz/zurb-foundation6-multiselect#2]
Sorry for bothering you again.

I have an array of 3000 and more Strings and the append process is very very very slow.
Have you got any ideas of how could be solved?

**Comment by icyz** [comment]
Try to show me your code

**Comment by Archetipo95** [comment]
``` 
var filepath = 'SECRET LINK';

$.get(filepath, function (data) {
	var lines = new Array(3024);
	lines = data.split(/\n/);
	var x = document.getElementById("menu");

	for (var line = 0; line < 3024; line++) {

		var option = document.createElement("option");
		option.text = lines[line];
		option.value = lines[line];
		x.add(option);
	}

	//<!--Activate zmultiselect on menu-->
	$("#menu").zmultiselect({
		filter: true,
		filterResult: true,
		selectAll: true,
		get: "zmultiselect",
		placeholder: "Column 1",
		live: '#menu_live'
	});
}); 
```

I improved loading speed but now the search is broken. With 3024 elements after typing the 2nd letter everything crash.

PS filepath is a link online of a file with 3024 strings (max 20 char per string) can't share the file sorry.

**Comment by icyz** [comment]
When I start with multiselect I did not imagine to have any select with 3000 items :-)

By the way, I've tried something like that: https://jsfiddle.net/ur5baefv/ and seems the issue is not "the append", but the event triggered when options are checked.

EDIT: clone the updated version and try now.
jsfiddle updated:  https://jsfiddle.net/ur5baefv/1/
